"""Analytical fixtures: expected values are specified independently of handlers."""
from __future__ import annotations

import hashlib
import math


def check(path, value, tolerance=1e-8, unit="1", reduction=None):
    return {"path":path,"expected":value,"absolute_tolerance":tolerance,"unit":unit,"reduction":reduction}


def case(skill, suite, params, checks, invalid, reason):
    return {"id":skill+"-analytic-v1","skill_id":skill,"suite":suite,"input":params,
            "checks":checks,"negative_patch":invalid,"failure_expectation":"ValueError/KeyError input contract rejection",
            "method_version":"1.0.0","reason":reason,"source_kind":"SYNTHETIC_ANALYTICAL",
            "regression_policy":"bit-identical canonical numerical output on repeat execution; special historical-edge fixtures where declared"}


def fixtures():
    fs=8192; n=1024; tone=[math.sin(2*math.pi*512*i/fs) for i in range(n)]
    mixed=[x+.1*math.sin(2*math.pi*1024*i/fs) for i,x in enumerate(tone)]
    text="Acoustic microphone sensitivity is voltage divided by sound pressure."
    rows=[
        case("product-system-plan","Product",{"product_index":3,"transducer":"Both","lifecycle":"EVT","risk":"R1","objective":"Verify earbud capture and playback baseline","requirements":[{"id":"FR1","minimum":-3,"maximum":3,"unit":"dB"}],"observations":[{"requirement_id":"FR1","value":1,"unit":"dB","evidence_ref":"synthetic-fixture"}]},[check("requirement_coverage",1),check("needed_skills",6,reduction="length")],{"product_index":24},"A valid product plan includes both transducer workstreams and preserves requirement coverage."),
        case("instrument-sequence","Product",{"sample_rate_hz":48000,"duration_s":1,"requested_rms_v":.1,"safe_rms_limit_v":.2,"mode":"SYNTHETIC_DRY_RUN"},[check("sample_count",48000,unit="samples"),check("physical_io_performed",False)],{"requested_rms_v":1},"Safe dry-run schedules the exact stimulus length and rejects excessive voltage without hardware IO."),
        case("spectral-analysis","DSP",{"samples":tone,"sample_rate_hz":fs,"window":"rectangular"},[check("amplitude.64",1),check("rms",math.sqrt(.5))],{"sample_rate_hz":0},"Coherent bin-64 sinusoid has unit peak amplitude and 1/sqrt(2) RMS."),
        case("response-phase-delay","DSP",{"frequency_hz":[100,200,300],"magnitude_db":[0,0,0],"phase_rad":[-2*math.pi*f*.001 for f in [100,200,300]],"smoothing_octaves":0},[check("group_delay_s",.001,unit="s",reduction="all")],{"frequency_hz":[100,100,300]},"Linear phase of a 1 ms delay has constant group delay."),
        case("harmonic-noise-analysis","DSP",{"samples":mixed,"sample_rate_hz":fs,"fundamental_hz":512,"harmonics":5},[check("thd_ratio",.1),check("thdn_ratio",.1)],{"fundamental_hz":fs},"Unit fundamental plus 0.1 second harmonic gives 10% THD, absent added noise."),
        case("time-frequency-analysis","DSP",{"samples":tone,"sample_rate_hz":fs,"segment_samples":256},[check("integrated_power",.5)],{"segment_samples":4},"Welch integration of a coherent unit sine conserves mean-square power."),
        case("transfer-coherence","DSP",{"reference":tone,"response":[2*x for x in tone],"sample_rate_hz":fs},[check("transfer_real",2,reduction="all"),check("coherence",1,reduction="all")],{"reference":[0]*n},"A noiseless gain-of-two system has H=2 and unit coherence in excited bins."),
        case("fractional-octave","DSP",{"samples":tone,"sample_rate_hz":fs,"fraction":3},[check("band_power_unit2",.5,reduction="sum")],{"fraction":0},"Nonoverlapping band power contains the coherent tone energy once."),
        case("frequency-weighting","DSP",{"samples":tone,"sample_rate_hz":fs,"weighting":"Z"},[check("rms",math.sqrt(.5))],{"weighting":"FAKE"},"Z weighting is unity gain."),
        case("microphone-sensitivity","Microphone",{"sensitivity_mv_per_pa":10,"noise_rms_v":1e-5,"signal_rms_v":.01},[check("signal_spl_db",93.97940008672037,unit="dB re 20 uPa"),check("snr_db",60,unit="dB"),check("sensitivity_dbv_per_pa",-40,unit="dBV/Pa")],{"sensitivity_mv_per_pa":0},"10 mV at 10 mV/Pa corresponds to 1 Pa RMS."),
        case("uncertainty-propagation","Failure",{"sensitivity_coefficients":[1,2],"standard_uncertainties":[.1,.2],"coverage_factor":2},[check("combined_standard_uncertainty",math.sqrt(.17)),check("expanded_uncertainty",2*math.sqrt(.17))],{"standard_uncertainties":[-.1,.2]},"Independent variance terms are 0.01 and 0.16."),
        case("repeatability-reproducibility","Failure",{"groups":[[1,2,3],[3,4,5]]},[check("repeatability_sd",1),check("between_group_sd",math.sqrt(5/3))],{"groups":[[1],[2]]},"Balanced random-effects calculation separates within-group variance from group means."),
        case("factorial-doe","Product",{"factors":{"gain":[0,2]},"responses":[0,4]},[check("main_effects.gain",4)],{"factors":{"gain":[2,0]}},"Single-factor effect equals high minus low response."),
        case("monte-carlo","Failure",{"means":[1,2],"standard_deviations":[1,1],"coefficients":[3,4],"trials":10000,"seed":7},[check("analytic_mean",11),check("analytic_sd",5),check("mean",11,.2)],{"trials":10},"Sum of independent normals has mean 11 and standard deviation 5."),
        case("correlation-outliers","Failure",{"x":[1,2,3,4,5],"y":[3,5,7,9,11]},[check("slope",2),check("intercept",1),check("pearson_r",1)],{"x":[1,1,1,1,1]},"Exact affine relation y=2x+1."),
        case("lumped-speaker","Speaker",{"moving_mass_kg":.01,"compliance_m_per_n":1/((2*math.pi*100)**2*.01),"mechanical_resistance_ns_per_m":1,"force_factor_n_per_a":5,"dc_resistance_ohm":4,"diaphragm_area_m2":.005,"frequency_hz":[50,100,200],"box_volume_m3":.001,"voltage_rms_v":1,"xmax_m":.01},[check("fs_hz",100,unit="Hz"),check("impedance_real_ohm.1",29,unit="ohm"),check("impedance_imag_ohm.1",0,unit="ohm")],{"moving_mass_kg":0},"At resonance the motional reactances cancel: Re + Bl squared/Rms = 29 ohm."),
        case("helmholtz-port","Speaker",{"area_m2":.001,"effective_length_m":.1,"volume_m3":.01,"sound_speed_m_s":343},[check("helmholtz_hz",343/(2*math.pi),unit="Hz")],{"effective_length_m":0},"Area/(length*volume)=1/m2 in the ideal Helmholtz model."),
        case("linear-array-pattern","Array",{"positions_m":[0,.02,.04,.06],"frequency_hz":1000,"sound_speed_m_s":343,"steering_deg":0},[check("normalized_power.180",1),check("alias_free_spacing",True)],{"positions_m":[0,0,.04,.06]},"Broadside in-phase sensors have normalized unit power."),
        case("gcc-phat-tdoa","Array",{"reference":[1.0 if i==100 else 0.0 for i in range(512)],"delayed":[1.0 if i==107 else 0.0 for i in range(512)],"sample_rate_hz":48000,"spacing_m":.1,"sound_speed_m_s":343},[check("delay_samples",7,unit="samples"),check("tdoa_s",7/48000,unit="s")],{"spacing_m":0},"A seven-sample shifted impulse establishes correlation lag sign and magnitude."),
        case("delay-sum-beamforming","Array",{"positions_m":[0,.02],"channels":[tone,tone],"sample_rate_hz":fs,"sound_speed_m_s":343,"steering_deg":0},[check("rms",math.sqrt(.5))],{"positions_m":[0,0]},"Averaging identical broadside channels preserves the source."),
        case("enhancement-aec-metrics","Microphone",{"clean":tone,"processed":mixed,"echo_before":tone,"echo_after":[.1*x for x in tone],"far_end_only":True},[check("si_sdr_db",20,unit="dB"),check("erle_db",20,unit="dB")],{"far_end_only":False},"Orthogonal 10% error gives SI-SDR 20 dB; 10x echo attenuation gives ERLE 20 dB."),
        case("room-ir-decay","Microphone",{"impulse_response":[math.exp(-math.log(1000)*(i/8000)/.6) for i in range(9600)],"sample_rate_hz":8000,"usable_decay_db":80},[check("t20_s",.6,.0001,"s"),check("t30_s",.6,.0001,"s")],{"impulse_response":[0]*128},"Exponential amplitude decay of 60 dB in 0.6 s yields the same extrapolated RT."),
        case("psychoacoustic-descriptors","Speaker",{"frequency_hz":[1000,3000],"power":[1,1]},[check("spectral_centroid_hz",2000,unit="Hz")],{"power":[-1,1]},"Equal energy at 1 and 3 kHz has a 2 kHz centroid; no MOS inference."),
        case("nvh-integration","Speaker",{"acceleration_m_s2":tone,"sample_rate_hz":fs},[check("velocity_rms_m_s",1/(math.sqrt(2)*2*math.pi*512),unit="m/s"),check("displacement_rms_m",1/(math.sqrt(2)*(2*math.pi*512)**2),unit="m")],{"sample_rate_hz":0},"Integration of a sine divides amplitude by angular frequency."),
        case("porous-absorption","Speaker",{"frequency_hz":[200,500,1000,2000],"flow_resistivity_pa_s_m2":10000,"thickness_m":.02},[check("absorption_normal_incidence",[0,1],reduction="range"),check("absorption_normal_incidence.2",.28505572817232716,1e-10)],{"flow_resistivity_pa_s_m2":1e9},"Passive rigid-backed fibrous layer; 1 kHz reference computed independently using scalar complex arithmetic and the stated Delany-Bazley equations."),
        case("thermal-rc","Speaker",{"power_w":2,"thermal_resistance_k_w":10,"thermal_capacity_j_k":5,"ambient_c":20,"limit_c":60,"time_s":[0,50,100]},[check("steady_temperature_c",40,unit="degC"),check("temperature_c.1",20+20*(1-math.exp(-1)),unit="degC")],{"thermal_capacity_j_k":0},"At one thermal time constant the rise is 1-exp(-1) of steady state."),
        case("leakage-tolerance","Microphone",{"radius_m":.001,"length_m":.01,"viscosity_pa_s":1.8e-5,"radius_standard_uncertainty_m":1e-5},[check("flow_resistance_pa_s_m3",8*1.8e-5*.01/(math.pi*1e-12),1e-6,"Pa s/m3")],{"radius_m":0},"Poiseuille resistance scales inversely with radius to the fourth power."),
        case("latency-budget","Product",{"sample_rate_hz":48000,"buffer_samples":[480,960],"other_stage_ms":[10,20],"clock_difference_ppm":50},[check("serial_latency_ms",60,unit="ms"),check("uncompensated_drift_ms_per_hour",180,unit="ms/hour")],{"buffer_samples":[-480,960]},"Thirty ms of buffers plus thirty ms of other serial stages."),
        case("local-audio-regression","Microphone",{"train_features":[[-2],[-1],[0],[1],[2]],"train_targets":[-3,-1,1,3,5],"validation_features":[[3],[4]],"validation_targets":[7,9],"train_ids":["a","b","c","d","e"],"validation_ids":["v1","v2"],"ridge":1e-6},[check("predictions.0",7,1e-5),check("validation_rmse",0,1e-5)],{"validation_ids":["a","v2"]},"Held-out affine regression without train/validation ID leakage."),
        case("butterworth-filter","DSP",{"samples":[1.0]+[0.0]*1023,"sample_rate_hz":fs,"cutoff_hz":[512],"order":4,"kind":"lowpass"},[check("filtered_samples",1,reduction="sum")],{"cutoff_hz":[fs]},"Stable unit-DC-gain lowpass impulse response sums to one."),
        case("level-statistics","Microphone",{"levels_db":[60,70],"durations_s":[1,1]},[check("leq_db",67.40362689494243,unit="dB"),check("l10_db",70,unit="dB")],{"durations_s":[0,1]},"Equal-duration energies average linearly, not as decibels."),
        case("resonance-characterization","Speaker",{"frequency_hz":[80,90,100,110,120],"amplitude":[.1,1/math.sqrt(2),1,1/math.sqrt(2),.1]},[check("peak_frequency_hz",100,unit="Hz"),check("q_estimate",5)],{"amplitude":[1,1,1,1,1]},"100 Hz resonance with half-power crossings at 90/110 Hz has Q=5."),
        case("circuit-noise-budget","Microphone",{"resistance_ohm":1000,"temperature_k":300,"bandwidth_hz":20000,"amplifier_noise_v_per_sqrt_hz":1e-9,"adc_fullscale_v":2,"adc_bits":16,"signal_frequency_hz":1000,"jitter_rms_s":1e-9},[check("quantization_rms_v",2/(65536*math.sqrt(12)),unit="V"),check("jitter_snr_limit_db",104.0364026328377,1e-7,"dB")],{"adc_bits":0},"Ideal uniform quantization variance is one LSB squared divided by 12."),
        case("engineering-requirements","Product",{"requirements":[{"id":"FR1","minimum":-3,"maximum":3,"unit":"dB"}],"observations":[{"requirement_id":"FR1","value":1,"unit":"dB","evidence_ref":"synthetic-case"}]},[check("coverage",1),check("checks.0.margin_to_nearest_limit",2,unit="dB")],{"observations":[{"requirement_id":"FR1","value":1,"unit":"Pa"}]},"A 1 dB observation is 2 dB inside the nearest +/-3 dB bound."),
        case("dfmea-ranking","Failure",{"failure_modes":[{"id":"F1","severity":10,"occurrence":2,"detection":5,"owner":"Chief","countermeasure":"limit voltage"}]},[check("ranked_modes.0.rpn",100),check("ranked_modes.0.human_review_required",True)],{"failure_modes":[{"id":"F1","severity":11,"occurrence":2,"detection":5}]},"High-severity mode remains Human-review required regardless of RPN ranking."),
        case("process-quality","Failure",{"values":[9,10,11,10,10],"lower_limit":7,"upper_limit":13},[check("mean",10),check("out_of_spec_count",0),check("ppk",math.sqrt(2))],{"values":[10]*5},"Sample SD=sqrt(0.5); centered Ppk=3/(3*SD)."),
        case("reliability-binomial","Failure",{"trials":100,"failures":0,"confidence":.95},[check("one_sided_upper_failure_probability",1-.05**.01)],{"failures":101},"Zero failures in 100 trials gives exact one-sided binomial bound."),
        case("failure-hypotheses","Failure",{"hypotheses":[{"id":"H1","support_refs":["E1"],"refute_refs":["E2"],"alternative_cause":"fixture leak","discriminating_test":"repeat with sealed fixture"}]},[check("hypotheses.0.refutation_count",1),check("hypotheses.0.root_cause_verified",False)],{"hypotheses":[{"id":"H1","support_refs":[],"refute_refs":[]}]},"Contradictory evidence leaves the cause contested and generates a discriminating test."),
        case("provenance-research","Product",{"query":"microphone sensitivity","documents":[{"id":"K1","title":"Sensitivity definition","text":text,"sha256":hashlib.sha256(text.encode()).hexdigest(),"rights":"AERIS_AUTHORED","source":"generated-method-note"}]},[check("matches.0.score",1)],{"documents":[{"rights":"UNLICENSED_PAID_FULLTEXT","source":"unknown"}]},"Local retrieval preserves document hash and rights classification."),
        case("requirement-traceability","Product",{"requirement_ids":["R1","R2"],"test_ids":["T1"],"links":[{"requirement_id":"R1","test_id":"T1","evidence_ref":"E1"}]},[check("coverage",.5)],{"links":[{"requirement_id":"UNKNOWN","test_id":"T1"}]},"One of two requirements has a test/evidence link; missing coverage remains visible."),
        case("experiment-optimization","Product",{"candidate_points":[[0],[1],[2]],"observations":[{"point":[0],"loss":5}]},[check("next_point.0",2),check("unexplored_count",2)],{"observations":[{"point":[9],"loss":0}]},"Maximin exploration selects the farthest allowed unexplored point without hardware actions."),
        case("evidence-counterreview","Failure",{"executor_role":"R015","reviewer_role":"R098","approved_evidence_refs":[],"claims":[{"classification":"EVIDENCE","evidence_refs":["invented"],"uncertainty":"not quantified","counter_hypothesis":"fixture error"}]},[check("findings",1,reduction="length")],{"reviewer_role":"R015"},"An independent rule-based reviewer rejects an unsupported Evidence claim."),
    ]
    return rows
