"""Independent reviews for bounded interactive-device product decisions."""
from __future__ import annotations
import math

def _same(a,e):
    if isinstance(e,dict):return isinstance(a,dict) and set(a)==set(e) and all(_same(a[k],v) for k,v in e.items())
    if isinstance(e,list):return isinstance(a,list) and len(a)==len(e) and all(_same(x,y) for x,y in zip(a,e))
    if isinstance(e,bool) or e is None:return a is e
    if isinstance(e,(int,float)):return isinstance(a,(int,float)) and not isinstance(a,bool) and math.isfinite(a) and math.isclose(a,e,rel_tol=1e-10,abs_tol=1e-12)
    return a==e

def review_gaming(p,candidate):
    from .personal_device_products import validate_gaming,_gaming_values
    validate_gaming(p);latency=_gaming_values(p)
    raw=[("SIDETONE_LATENCY",latency,p["maximum_sidetone_latency_ms"],"<=","REDUCE_CAPTURE_PROCESSING_OR_PLAYBACK_BUFFER"),("BOOM_DISTANCE_MINIMUM",p["boom_mic_distance_m"],p["minimum_boom_distance_m"],">=","MOVE_BOOM_AWAY_FROM_PLOSIVE_ZONE"),("BOOM_DISTANCE_MAXIMUM",p["boom_mic_distance_m"],p["maximum_boom_distance_m"],"<=","MOVE_BOOM_TOWARD_NEARFIELD_SPEECH"),("PLAYBACK_CROSSTALK",p["speaker_to_mic_crosstalk_db"],p["maximum_crosstalk_db"],"<=","REVISE_EARCUP_ISOLATION_BOOM_OR_AEC_PATH"),("VOICE_SNR",p["voice_snr_db"],p["minimum_voice_snr_db"],">=","REVISE_BOOM_POSITION_NOISE_REDUCTION_OR_GAIN"),("OUTPUT_HEADROOM",p["output_headroom_db"],p["minimum_output_headroom_db"],">=","REDUCE_PLAYBACK_GAIN_OR_REVISE_OUTPUT_CHAIN")]
    rows=[{"id":i,"actual":a,"limit":l,"operator":o,"passed":a<=l if o=="<=" else a>=l,"on_failure":f} for i,a,l,o,f in raw]
    expected={"sidetone_latency_ms":latency,"microphone_topology":p["microphone_topology"],"checks":rows,"required_revisions":[r["on_failure"] for r in rows if not r["passed"]],"disposition":"BOUNDED_BASELINE_ACCEPT" if all(r["passed"] for r in rows) else "DESIGN_REVISION_REQUIRED","plosive_performance_verified":False,"communication_quality_verified":False,"physical_call_verified":False,"physical_measurement_verified":False,"counter_hypotheses":["Boom distance rather than noise-reduction defect","Playback leakage rather than network echo","Local buffering rather than network latency"],"next_discriminating_experiment":"MEASURE_LOCAL_SIDETONE_BOOM_PLOSIVE_CROSSTALK_AND_CALL_QUALITY_ACROSS_USERS","model_assumptions":["Local sidetone stages add serially","Boom distance is a supplied scalar proxy","Crosstalk, SNR and headroom share a declared operating state"],"unresolved":["Plosive directivity and user boom placement distribution","Codec/network path and nonlinear AEC behavior","Physical call quality and qualified Human acceptance"]}
    return _finish("gaming-communication-latency",candidate,expected,"sidetone/boom/crosstalk/SNR/headroom")

def review_smartphone(p,candidate):
    from .personal_device_products import validate_smartphone
    validate_smartphone(p)
    raw=[("HAND_BLOCKAGE",p["hand_blockage_loss_db"],p["maximum_hand_blockage_loss_db"],"<=","REVISE_PORT_DISTRIBUTION_OR_ORIENTATION_ROUTING"),("WATER_MESH_LOSS",p["water_mesh_loss_db"],p["maximum_water_mesh_loss_db"],"<=","REVISE_MESH_PORT_OR_GAIN_BUDGET"),("ECHO_COUPLING",p["speaker_to_mic_echo_coupling_db"],p["maximum_echo_coupling_db"],"<=","REVISE_SPEAKER_MIC_ISOLATION_OR_AEC_RANGE"),("ORIENTATION_COVERAGE",p["orientation_count"],p["minimum_orientation_count"],">=","EXPAND_HANDHELD_VIDEO_SPEAKERPHONE_ORIENTATION_MATRIX"),("BOTTOM_SPEAKER_EXCURSION",p["bottom_speaker_peak_excursion_mm"],p["safe_bottom_speaker_excursion_mm"],"<=","LIMIT_BASS_DRIVE_OR_REVISE_BOTTOM_SPEAKER"),("HANDHELD_CALL_SNR",p["handheld_call_snr_db"],p["minimum_handheld_call_snr_db"],">=","REVISE_MIC_SELECTION_PORT_OR_NOISE_REDUCTION")]
    rows=[{"id":i,"actual":a,"limit":l,"operator":o,"passed":a<=l if o=="<=" else a>=l,"on_failure":f} for i,a,l,o,f in raw]
    expected={"port_protection":p["port_protection"],"checks":rows,"required_revisions":[r["on_failure"] for r in rows if not r["passed"]],"disposition":"BOUNDED_BASELINE_ACCEPT" if all(r["passed"] for r in rows) else "DESIGN_REVISION_REQUIRED","mesh_transfer_verified":False,"hand_population_verified":False,"aec_verified":False,"physical_handset_verified":False,"physical_measurement_verified":False,"counter_hypotheses":["Hand blockage rather than speaker defect","Water mesh loss rather than capsule sensitivity shift","Mechanical coupling rather than AEC algorithm regression"],"next_discriminating_experiment":"MEASURE_PORT_MESH_HAND_ORIENTATION_ECHO_AND_EXCURSION_ON_REFERENCED_HANDSETS","model_assumptions":["Blockage and mesh losses are supplied scalar maxima","Echo coupling uses one declared level convention","Orientation count is coverage metadata, not a population result"],"unresolved":["Frequency-dependent hand/mesh transfer and unit variation","Nonlinear speaker excursion and time-varying echo path","Physical handset, call quality and qualified Human acceptance"]}
    return _finish("smartphone-port-mesh-echo",candidate,expected,"hand/mesh/echo/orientation/excursion/SNR")

def review_tablet(p,candidate):
    from .personal_device_products import validate_tablet
    validate_tablet(p)
    raw=[("ORIENTATION_MODE_COVERAGE",p["orientation_mode_count"],p["minimum_orientation_mode_count"],">=","EXPAND_PORTRAIT_LANDSCAPE_AND_TABLE_MATRIX"),("CASE_BLOCKED_EDGE_PORTS",p["blocked_edge_port_count"],p["maximum_blocked_edge_port_count"],"<=","REVISE_CASE_CUTOUT_OR_EDGE_PORT_ROUTING"),("CASE_PORT_CLEARANCE",p["case_port_clearance_mm"],p["minimum_case_port_clearance_mm"],">=","INCREASE_CASE_TO_PORT_CLEARANCE"),("TABLE_REFLECTION_DELAY",p["table_reflection_delay_ms"],p["minimum_table_reflection_delay_ms"],">=","REVISE_TABLE_PLACEMENT_ARRAY_STEERING_OR_GATING"),("STEREO_BALANCE",p["stereo_balance_error_db"],p["maximum_stereo_balance_error_db"],"<=","REMAP_OR_EQUALIZE_ORIENTATION_DEPENDENT_EDGE_SPEAKERS"),("ARRAY_STEERING",p["array_steering_error_deg"],p["maximum_array_steering_error_deg"],"<=","RECALCULATE_ORIENTATION_AND_TABLE_REFLECTION_STEERING")]
    rows=[{"id":i,"actual":a,"limit":l,"operator":o,"passed":a<=l if o=="<=" else a>=l,"on_failure":f} for i,a,l,o,f in raw]
    expected={"placement_set":p["placement_set"],"checks":rows,"required_revisions":[r["on_failure"] for r in rows if not r["passed"]],"disposition":"BOUNDED_BASELINE_ACCEPT" if all(r["passed"] for r in rows) else "DESIGN_REVISION_REQUIRED","case_transfer_verified":False,"table_reflection_verified":False,"orientation_population_verified":False,"physical_tablet_verified":False,"physical_measurement_verified":False,"counter_hypotheses":["Orientation mapping rather than speaker mismatch","Case interference rather than capsule variation","Table reflection rather than beamformer defect"],"next_discriminating_experiment":"MEASURE_CASE_PORT_TRANSFER_AND_ARRAY_RESPONSE_IN_PORTRAIT_LANDSCAPE_HANDHELD_AND_TABLE_STATES","model_assumptions":["Placement modes are supplied categorical coverage","Port clearance and reflection delay are scalar design proxies","Balance and steering errors share a declared reference state"],"unresolved":["Frequency-dependent case and table transfer","User grip and case population distribution","Physical tablet, speech quality and qualified Human acceptance"]}
    return _finish("tablet-orientation-case-table",candidate,expected,"orientation/case/table-reflection/balance/steering")

def review_laptop(p,candidate):
    from .personal_device_products import validate_laptop
    validate_laptop(p)
    raw=[("FAN_HARMONIC_CAPTURE",p["fan_harmonic_capture_db"],p["maximum_fan_harmonic_capture_db"],"<=","REVISE_FAN_STATE_CAPTURE_NOTCH_OR_MIC_PLACEMENT"),("HINGE_ANGLE_COVERAGE",p["hinge_angle_count"],p["minimum_hinge_angle_count"],">=","EXPAND_HINGE_ANGLE_TRANSFER_MATRIX"),("ARRAY_TRANSFER_SPREAD",p["array_transfer_spread_db"],p["maximum_array_transfer_spread_db"],"<=","REVISE_BEZEL_ARRAY_OR_HINGE_DEPENDENT_PROCESSING"),("KEYBOARD_BODY_COUPLING",p["keyboard_body_coupling_db"],p["maximum_keyboard_body_coupling_db"],"<=","ISOLATE_KEYBOARD_BODY_PATH_BEFORE_AEC_RETUNING"),("SPEAKER_HEADROOM",p["speaker_headroom_db"],p["minimum_speaker_headroom_db"],">=","REDUCE_OUTPUT_GAIN_OR_REVISE_SPEAKER_CHAIN"),("AEC_REFERENCE_ALIGNMENT",p["aec_reference_alignment_ms"],p["maximum_aec_reference_alignment_ms"],"<=","ALIGN_PLAYBACK_REFERENCE_BEFORE_ECHO_ADAPTATION")]
    rows=[{"id":i,"actual":a,"limit":l,"operator":o,"passed":a<=l if o=="<=" else a>=l,"on_failure":f} for i,a,l,o,f in raw]
    expected={"fan_operating_set":p["fan_operating_set"],"checks":rows,"required_revisions":[r["on_failure"] for r in rows if not r["passed"]],"disposition":"BOUNDED_BASELINE_ACCEPT" if all(r["passed"] for r in rows) else "DESIGN_REVISION_REQUIRED","fan_path_verified":False,"hinge_transfer_verified":False,"aec_verified":False,"physical_laptop_verified":False,"physical_measurement_verified":False,"counter_hypotheses":["Structural coupling rather than AEC failure","Thermal policy rather than microphone defect","Hinge transfer rather than fixed array calibration error"],"next_discriminating_experiment":"MEASURE_FAN_HARMONICS_KEYBOARD_COUPLING_AND_BEZEL_ARRAY_TRANSFER_ACROSS_HINGE_AND_THERMAL_STATES","model_assumptions":["Fan harmonic and coupling values use one declared reference","Hinge count is coverage metadata, not continuous transfer","Headroom and AEC alignment are supplied scalar budgets"],"unresolved":["Continuous hinge-angle acoustic transfer and fan order tracking","Keyboard/body modal paths and thermal policy variation","Physical laptop, call quality and qualified Human acceptance"]}
    return _finish("laptop-fan-hinge-coupling",candidate,expected,"fan/hinge/array/body-coupling/headroom/AEC-reference")

def _finish(domain,candidate,expected,scope):
    if not isinstance(candidate,dict) or set(candidate)!=set(expected):raise ValueError("exact product assertions required")
    differences=[{"field":k,"asserted":candidate[k],"expected":v} for k,v in expected.items() if not _same(candidate[k],v)]
    return {"domain":domain,"decision":"CHANGES_REQUIRED" if differences else "BOUNDED_REVIEW_ACCEPT","disagreements":differences,"observations":{"bounded_scope":scope,"unresolved":"physical product distribution and Human acceptance"},"human_approval":False,"role_l3_awarded":False,"scope":"bounded product report consistency only"}
