"""Reviewed explicit seat mappings and product-specific planning knowledge."""
from __future__ import annotations

# Ordered by read-only Core canonical IDs, never inferred from keyword matching.
SEAT_SKILLS = [
    "engineering-requirements requirement-traceability dfmea-ranking", # R001
    "lumped-speaker engineering-requirements thermal-rc",
    "microphone-sensitivity linear-array-pattern engineering-requirements",
    "engineering-requirements latency-budget requirement-traceability",
    "spectral-analysis butterworth-filter enhancement-aec-metrics",
    "uncertainty-propagation process-quality evidence-counterreview",
    "process-quality reliability-binomial dfmea-ranking",
    "provenance-research requirement-traceability evidence-counterreview",
    "lumped-speaker helmholtz-port engineering-requirements", # R009 Speaker
    "lumped-speaker resonance-characterization harmonic-noise-analysis",
    "helmholtz-port lumped-speaker linear-array-pattern",
    "circuit-noise-budget transfer-coherence engineering-requirements",
    "circuit-noise-budget thermal-rc lumped-speaker",
    "latency-budget circuit-noise-budget spectral-analysis",
    "response-phase-delay harmonic-noise-analysis resonance-characterization",
    "harmonic-noise-analysis thermal-rc reliability-binomial",
    "linear-array-pattern response-phase-delay",
    "response-phase-delay fractional-octave psychoacoustic-descriptors",
    "lumped-speaker butterworth-filter thermal-rc",
    "psychoacoustic-descriptors frequency-weighting level-statistics",
    "lumped-speaker helmholtz-port",
    "nvh-integration linear-array-pattern",
    "room-ir-decay linear-array-pattern",
    "butterworth-filter spectral-analysis harmonic-noise-analysis",
    "lumped-speaker thermal-rc latency-budget",
    "room-ir-decay response-phase-delay butterworth-filter",
    "microphone-sensitivity linear-array-pattern engineering-requirements", # R027 Microphone
    "microphone-sensitivity circuit-noise-budget",
    "leakage-tolerance porous-absorption nvh-integration",
    "circuit-noise-budget microphone-sensitivity transfer-coherence",
    "circuit-noise-budget spectral-analysis latency-budget",
    "latency-budget spectral-analysis transfer-coherence",
    "microphone-sensitivity harmonic-noise-analysis level-statistics",
    "linear-array-pattern gcc-phat-tdoa uncertainty-propagation",
    "enhancement-aec-metrics room-ir-decay level-statistics",
    "response-phase-delay butterworth-filter",
    "linear-array-pattern delay-sum-beamforming",
    "enhancement-aec-metrics psychoacoustic-descriptors",
    "leakage-tolerance helmholtz-port porous-absorption",
    "linear-array-pattern gcc-phat-tdoa delay-sum-beamforming",
    "room-ir-decay porous-absorption nvh-integration",
    "enhancement-aec-metrics transfer-coherence latency-budget",
    "gcc-phat-tdoa delay-sum-beamforming linear-array-pattern",
    "enhancement-aec-metrics local-audio-regression butterworth-filter",
] + ["product-system-plan engineering-requirements requirement-traceability dfmea-ranking"]*24 + [
    "psychoacoustic-descriptors frequency-weighting level-statistics", # R069 Experts
    "enhancement-aec-metrics correlation-outliers",
    "gcc-phat-tdoa linear-array-pattern latency-budget",
    "room-ir-decay fractional-octave",
    "nvh-integration resonance-characterization",
    "porous-absorption leakage-tolerance",
    "thermal-rc reliability-binomial",
    "circuit-noise-budget spectral-analysis transfer-coherence",
    "leakage-tolerance monte-carlo",
    "factorial-doe monte-carlo correlation-outliers",
    "uncertainty-propagation repeatability-reproducibility",
    "latency-budget correlation-outliers gcc-phat-tdoa",
    "latency-budget circuit-noise-budget",
    "latency-budget transfer-coherence",
    "latency-budget enhancement-aec-metrics",
    "local-audio-regression time-frequency-analysis",
    "requirement-traceability provenance-research",
    "correlation-outliers engineering-requirements repeatability-reproducibility",
    "provenance-research evidence-counterreview",
    "factorial-doe experiment-optimization provenance-research",
    "provenance-research requirement-traceability", # R089 Ops
    "engineering-requirements requirement-traceability",
    "engineering-requirements experiment-optimization",
    "instrument-sequence uncertainty-propagation",
    "process-quality engineering-requirements",
    "failure-hypotheses dfmea-ranking",
    "process-quality repeatability-reproducibility",
    "reliability-binomial thermal-rc",
    "requirement-traceability engineering-requirements",
    "evidence-counterreview dfmea-ranking",
    "requirement-traceability provenance-research evidence-counterreview",
    "experiment-optimization factorial-doe monte-carlo",
]

# Speaker topology | microphone topology | usage | characteristic risks
PRODUCT_KNOWLEDGE = [
    ("receiver-in-canal, vented earmold","matched dual MEMS, protected ports","speech intelligibility at prescribed fitting","feedback;occlusion;unsafe gain;clinical applicability"),
    ("receiver with user-adjustable gain","dual external microphones","consumer self-fit listening","output exposure;fit variability;misuse as clinical device"),
    ("ear-level receiver or neckloop interface","optional remote talker microphone","public assistive broadcast listening","broadcast latency;interoperability;accessibility"),
    ("sealed miniature dynamic/BA driver","feedforward, feedback and voice microphones","music and calls while walking","seal leakage;wind;ANC instability;occlusion"),
    ("circumaural driver and ear-cup cavity","inside/outside ANC and voice microphones","travel and office listening","cushion seal;feedback stability;pressure sensation"),
    ("stereo near-ear drivers","boom microphone or short array","gaming and two-way communication","sidetone delay;plosive noise;crosstalk"),
    ("earpiece plus bottom stereo driver","distributed front/back/bottom microphones","handheld calls, video and speakerphone","hand blocking;water mesh;echo coupling"),
    ("distributed edge speakers","edge/front capture array","landscape video and conferencing","orientation;table reflections;case blockage"),
    ("keyboard/base speakers with limited enclosure","display-bezel array","desk conferencing and media","fan noise;hinge orientation;structure coupling"),
    ("display-integrated speakers","top-bezel conferencing microphones","desktop playback and video meetings","desk reflection;USB scheduling;power supply noise"),
    ("woofer/tweeter with compact enclosure","circular far-field array","voice assistant with concurrent playback","self-echo;room modes;grating lobes"),
    ("linear multiway bar plus optional subwoofer","optional voice-assistant array","TV dialogue and virtual surround","TV wall boundary;lip sync;crossover mismatch"),
    ("multichannel satellites and subwoofer","calibration microphone plus optional voice mic","room-scale immersive playback","channel polarity;time alignment;room modes"),
    ("down/back-firing thin display drivers","optional bezel voice array","living-room broadcast and dialogue","panel buzz;wall placement;dialogue masking"),
    ("weather-protected small loudspeaker","weather mesh-protected microphone","outdoor two-way door communication","wind;water ingress;feedback;vandal exposure"),
    ("small notification/speech driver","single or short-array voice capture","appliance controls and notifications","motor noise;enclosure leaks;duty-cycle heat"),
    ("open-ear temples or directional speakers","small distributed temple array","mobile AR prompts and communication","sound leakage;wind;head position;privacy"),
    ("near-ear/open-ear stereo","headset distributed capture microphones","immersive head-tracked interaction","motion-to-sound latency;occlusion;mechanical rubbing"),
    ("cabin multiway speakers","headliner/cabin hands-free array","driving, media and telephony","road noise;seat variation;echo;thermal range"),
    ("warning/interaction speaker","chassis-mounted distributed microphones","mobile autonomous vehicle interaction","motor vibration;Doppler;warning audibility"),
    ("rugged local interaction speaker","isolated body/head microphones","walking robot field interaction","impact noise;motor harmonics;orientation changes"),
    ("head/chest speech speaker","head/body conversational array","human-facing service interaction","self-generated speech echo;mechanical motion;privacy"),
    ("conference speakerphone or distributed playback","tabletop or ceiling array","full-duplex multi-talker conferencing","double-talk;AEC tail;room reverberation"),
    ("optional monitoring/output speaker","linear/planar directional array","targeted speech pickup","spatial aliasing;calibration mismatch;front/back ambiguity"),
]


def product_profile(index: int) -> dict:
    if not 0<=index<24: raise ValueError("canonical product index must be 0..23")
    speaker,mic,scenario,risks=PRODUCT_KNOWLEDGE[index]
    return {"speaker_topology_considerations":speaker,"microphone_topology_considerations":mic,
            "usage_scenarios":[scenario],"common_acoustic_failure_modes":risks.split(";"),
            "lifecycle":["Concept","EVT","DVT","PVT","MP","Field"],
            "measurement_plan":["declare fixture/geometry and calibration state","capture raw FR/noise/IR and electrical limits",
                                "repeat across fit/orientation/operating conditions","compare required bands and uncertainty margins"],
            "simulation_requirements":["linear speaker/port baseline where topology applies","array propagation and room/latency budgets where capture applies"],
            "manufacturing_risks":["assembly leakage and tolerances","component sensitivity variation","EOL limits without justified guard bands"],
            "standards_metadata_references":["IEC 60268-5","IEC 60268-4"],
            "evidence_expectations":["raw-data hash","fixture and calibration provenance","method version","uncertainty","counter-hypothesis review"],
            "non_scope":["clinical efficacy or patient fitting","licensed-tool equivalence","physical qualification without measurements"]}
