#!/usr/bin/env python3
"""Generate a new release-authority signing key for the Human Chief Engineer
(or another principal) and register it in the local trust store.

This is the ONE manual step nothing in aeris_runtime does automatically: the
Human's key must be generated by the Human, not by AERIS itself, or a G5
release approval signed with it would not represent a genuine independent
review -- see aeris_runtime/release_attestation.py's module docstring.

Usage (run this yourself, once, on this machine):

    python scripts/authority-keygen.py --subject-id "your-name" --human

The generated 32-byte key is printed ONCE to your terminal and written to
.aeris/authority/<subject-id>.key -- keep that file safe; anyone who reads it
can sign release approvals as you. Losing it just means running this again
under a new subject-id (the old principal can be revoked in trust.json).
"""
from __future__ import annotations

import argparse
import json
import re
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TRUST_STORE = ROOT / ".aeris" / "authority" / "trust.json"
KEY_DIR = ROOT / ".aeris" / "authority"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--subject-id", required=True, help="A stable identifier for you, e.g. your name (no spaces).")
    parser.add_argument("--signer-id", default=None, help="Trust-store key name (defaults to subject-id).")
    parser.add_argument("--human", action="store_true", help="Register as the Human Chief Engineer (required for G5 approval).")
    args = parser.parse_args()

    if not re.fullmatch(r"[A-Za-z0-9_-]{1,60}", args.subject_id):
        print("subject-id must be letters/digits/-/_ only, max 60 chars", file=sys.stderr)
        return 1
    signer_id = args.signer_id or args.subject_id

    KEY_DIR.mkdir(parents=True, exist_ok=True)
    key_path = KEY_DIR / f"{args.subject_id}.key"
    if key_path.exists():
        print(f"A key already exists at {key_path}. Refusing to overwrite it.", file=sys.stderr)
        print("If you genuinely need a new key, choose a different --subject-id, or", file=sys.stderr)
        print("revoke the old principal in trust.json and delete the old key file yourself.", file=sys.stderr)
        return 1

    key = secrets.token_bytes(32)
    key_path.write_text(key.hex(), encoding="utf-8")

    trust = {"principals": {}}
    if TRUST_STORE.is_file():
        trust = json.loads(TRUST_STORE.read_text(encoding="utf-8"))
    trust.setdefault("principals", {})[signer_id] = {
        "key_hex": key.hex(),
        "revoked": False,
        "subject_id": args.subject_id,
        "kind": "HUMAN" if args.human else "REVIEWER",
        **({"human_authority": "Human Chief Engineer"} if args.human else {}),
        "allowed_gates": ["G4_INDEPENDENT_REVIEW", "G5_APPROVAL"] if args.human else ["G4_INDEPENDENT_REVIEW"],
        "isolated_contexts": [f"{args.subject_id}_review_context"],
    }
    TRUST_STORE.parent.mkdir(parents=True, exist_ok=True)
    TRUST_STORE.write_text(json.dumps(trust, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"Key generated and saved to: {key_path}")
    print(f"Registered in the trust store as signer_id={signer_id!r}, kind={'HUMAN' if args.human else 'REVIEWER'}.")
    print("Keep the key file safe -- it is the only copy that matters going forward.")
    print("\nNext step: run scripts/prepare-release-attestation.py, then")
    print(f"  scripts/mint-g5-approval.py --key-file \"{key_path}\" --signer-id {signer_id}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
