const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];let roles=[],lastPod=null;
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const j=await r.json();if(!r.ok)throw new Error(j.detail||j.error||`HTTP ${r.status}`);return j}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function currentTheme(){return document.documentElement.dataset.theme==='light'?'light':'dark'}
function applyTheme(theme){document.documentElement.dataset.theme=theme==='light'?'light':'dark';const toggle=$('#themeToggle');if(toggle){const light=currentTheme()==='light';toggle.textContent=light?'◐':'☀';toggle.title=light?'切換深色模式':'切換淺色模式';toggle.setAttribute('aria-label',toggle.title)}}
function themedPath(name){const path=name==='dashboard'?'/':'/'+name;return `${path}?theme=${currentTheme()}`}
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===name));$$('.nav[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));history.replaceState(null,'',themedPath(name))}
$$('.nav[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$('#themeToggle').addEventListener('click',()=>{applyTheme(currentTheme()==='dark'?'light':'dark');const active=$('.view.active-view')?.id||'dashboard';history.replaceState(null,'',themedPath(active))});
function maturity(status){const c=status.maturity?.counts||{},total=Object.values(c).reduce((a,b)=>a+b,0)||1;$('#maturityBars').innerHTML=Object.entries(c).sort().map(([k,v])=>`<div class="maturity-row"><span>${esc(k)}</span><div class="bar"><i style="width:${Math.round(v/total*100)}%"></i></div><b>${v}</b></div>`).join('')}
function renderExpectedRuns(x){const box=$('#expectedRuns');if(!box)return;const runs=x?.runs||[];box.innerHTML=runs.length?`<div class="task-card"><strong>Overall · ${esc(x.overall)}</strong><small>Expected artifact / freshness monitor</small></div>`+runs.map(r=>`<div class="task-card"><strong>${esc(r.name)} · ${esc(r.state)}</strong><small>${esc(r.reason||'')}</small><p>${esc(r.scope||'')}</p></div>`).join(''):`<div class="empty">NOT_CONFIGURED — 尚無 expected-run contract</div>`}
async function loadStatus(){try{const s=await api('/api/v1/status');$('#opening').textContent=s.company_opening_state;$('#roleCount').textContent=s.role_count;$('#skillCount').textContent=s.skill_count??0;$('#knowledgeCount').textContent=s.knowledge?.documents??0;$('#taskCount').textContent=s.control?.active_tasks??0;$('#modelState').textContent=s.local_provider_ready?'READY':'LIMITED';$('#modelName').textContent=s.local_model||'—';$('#companyStatus').textContent=JSON.stringify({opening:s.company_opening_state,runtime_mode:s.runtime_mode,local_model:s.local_model,local_provider_ready:s.local_provider_ready,roles:s.role_count,skills:s.skill_count,workflow_templates:s.workflow_template_count,workflow_runs:s.workflow_run_count,projects:s.control?.projects,tasks:s.control?.tasks,knowledge:s.knowledge?.documents,expected_runs:s.expected_runs?.overall,company_complete:s.company_complete},null,2);maturity(s);renderExpectedRuns(s.expected_runs)}catch(e){$('#opening').textContent='ERROR';$('#companyStatus').textContent=e.message}}
async function loadProjects(){const d=await api('/api/v1/projects');$('#projectSelect').innerHTML=d.projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)} (${p.task_count})</option>`).join('')}
async function loadTasks(){const d=await api('/api/v1/tasks');$('#taskList').innerHTML=d.tasks.length?d.tasks.map(t=>`<div class="task-card"><strong>${esc(t.title)}</strong><small>${esc(t.id)} · ${esc(t.state)} · ${esc(t.risk_level)}</small><p>${esc(t.description||'')}</p>${t.pod?`<small>Pod ${t.pod.pod_size} 席</small>`:''}</div>`).join(''):'<div class="empty">尚無任務</div>'}
async function loadRoles(){const d=await api('/api/v1/roles');roles=d.roles;renderRoles('')}
function renderRoles(filter){const q=filter.toLowerCase();const list=roles.filter(r=>!q||r.name.toLowerCase().includes(q)||r.group.toLowerCase().includes(q)||r.id.toLowerCase().includes(q));$('#allRoles').innerHTML=list.map(r=>`<div class="role-card" data-role="${esc(r.id)}"><strong>${esc(r.id)} · ${esc(r.name)}</strong><small>${esc(r.group)} · ${esc(r.execution_state)}</small></div>`).join('')}
function renderPod(p){lastPod=p;$('#podMeta').textContent=`${p.pod_size} 席 · ${p.planner}`;$('#podRoles').classList.remove('empty');$('#podRoles').innerHTML=p.roles.map((r,i)=>`<div class="role-card"><strong>${i===0?'LEAD · ':''}${esc(r.id)} · ${esc(r.name)}</strong><small>${esc(r.group)} · ${esc(r.domain)}</small></div>`).join('')}
async function loadSkills(){try{const d=await api('/api/v1/skills');$('#skillList').innerHTML=d.skills?.length?d.skills.map(x=>`<div class="task-card"><strong>${esc(x.skill_id||x.id||x.name)}</strong><small>${esc(x.version||'')} · ${esc(x.execution||x.execution_state||'deterministic')}</small><p>${esc(x.description||x.purpose||'')}</p></div>`).join(''):'<div class="empty">尚無 Skill</div>'}catch(e){$('#skillList').textContent=e.message}}
async function loadWorkflows(){try{const [templates,runs]=await Promise.all([api('/api/v1/workflow-templates'),api('/api/v1/workflows')]);const t=(templates.templates||[]).map(x=>`<div class="task-card"><strong>TEMPLATE · ${esc(x.name||x.template_id)}</strong><small>${esc(x.template_id)} · ${esc(x.execution_state)}</small><p>Skill: ${esc(x.skill_id)} · Risk: ${esc(x.default_risk)}</p></div>`);const r=(runs.workflows||[]).map(x=>`<div class="task-card"><strong>RUN · ${esc(x.workflow_id||x.id||x.task_id||'workflow')}</strong><small>${esc(x.state||x.status||'')}</small><p>${esc(x.execution?.skill_id||x.summary||'')}</p></div>`);$('#workflowList').innerHTML=[...t,...r].join('')||'<div class="empty">尚無 Workflow template 或 run</div>'}catch(e){$('#workflowList').textContent=e.message}}
async function searchStandards(){try{const q=$('#standardQuery').value.trim();const d=await api('/api/v1/standards?q='+encodeURIComponent(q));$('#standardResults').innerHTML=d.standards?.length?d.standards.map(x=>`<div class="search-item"><strong>${esc(x.id||x.standard_id||x.designation||'STANDARD')}</strong><small> ${esc(x.edition||x.revision||'')} · ${esc(x.status||'UNKNOWN')}</small><p>${esc(x.title||x.scope||'')}</p></div>`).join(''):'<div class="empty">沒有結果</div>'}catch(e){$('#standardResults').textContent=e.message}}
$('#refreshStatus').addEventListener('click',loadStatus);$('#refreshTasks').addEventListener('click',loadTasks);$('#roleFilter').addEventListener('input',e=>renderRoles(e.target.value));
$('#planPod').addEventListener('click',async()=>{const q=$('#taskDescription').value.trim()||$('#taskTitle').value.trim();if(!q)return;try{renderPod(await api('/api/v1/pods/plan',{method:'POST',body:JSON.stringify({query:q,max_roles:8})}))}catch(e){$('#podRoles').textContent=e.message}});
$('#createTask').addEventListener('click',async()=>{const title=$('#taskTitle').value.trim(),description=$('#taskDescription').value.trim();if(!title)return;try{await api('/api/v1/tasks',{method:'POST',body:JSON.stringify({project_id:$('#projectSelect').value,title,description,risk_level:$('#riskLevel').value,auto_pod:true,max_roles:8})});$('#taskTitle').value='';$('#taskDescription').value='';lastPod=null;await Promise.all([loadTasks(),loadStatus(),loadProjects()])}catch(e){alert(e.message)}});
$('#invokeLead').addEventListener('click',async()=>{if(!lastPod?.roles?.length){$('#invokeResult').textContent='請先規劃 Dynamic Pod';return}const prompt=$('#invokePrompt').value.trim()||$('#taskDescription').value.trim();if(!prompt){$('#invokeResult').textContent='請輸入問題';return}const lead=lastPod.roles[0];$('#invokeResult').textContent=`${lead.name} 執行中…`;try{const d=await api(`/api/v1/roles/${lead.id}/invoke`,{method:'POST',body:JSON.stringify({prompt})});$('#invokeResult').textContent=`[${d.role.id} ${d.role.name}]\nProvider: ${d.provider}\nModel: ${d.model}\n\n${d.text}`}catch(e){$('#invokeResult').textContent=`執行失敗：${e.message}`}});
$('#knowledgeSearch').addEventListener('click',async()=>{const q=$('#knowledgeQuery').value.trim();if(!q)return;try{const d=await api('/api/v1/knowledge/search?q='+encodeURIComponent(q));$('#knowledgeResults').innerHTML=d.results.length?d.results.map(x=>`<div class="search-item"><small>${esc(x.path)} · ${esc(x.search_engine)}</small><p>${esc(x.snippet)}</p></div>`).join(''):'<div class="empty">沒有結果</div>'}catch(e){$('#knowledgeResults').textContent=e.message}});
$('#standardSearch').addEventListener('click',searchStandards);$('#standardQuery').addEventListener('keydown',e=>{if(e.key==='Enter')searchStandards()});
async function loadAudit(){try{const d=await api('/api/v1/audit?limit=20');$('#auditList').innerHTML=d.records.length?d.records.map(r=>`<div class="audit-item"><code>${esc(r.event_type||r.type||'EVENT')}</code><small> ${esc(r.timestamp_utc||r.timestamp||'')}</small><p>${esc(r.actor||'')} ${esc(JSON.stringify(r.data||r.payload||{})).slice(0,220)}</p></div>`).join(''):'<div class="empty">尚無 Audit 紀錄</div>'}catch(e){$('#auditList').textContent=e.message}}
$('#allRoles').addEventListener('click',e=>{const c=e.target.closest('[data-role]');if(!c)return;const r=roles.find(x=>x.id===c.dataset.role);if(r){lastPod={pod_size:1,planner:'manual_role_selection',roles:[r]};switchView('workspace');renderPod(lastPod);$('#invokePrompt').focus()}});
const pageParams=new URLSearchParams(location.search);const visualBaseline=pageParams.get('visual_baseline')==='1';window.AERIS_VISUAL_BASELINE=visualBaseline;applyTheme(pageParams.get('theme'));const initial=location.pathname.replace('/','')||'dashboard';if(['dashboard','workspace','services'].includes(initial))switchView(initial);
if(!visualBaseline){Promise.allSettled([loadStatus(),loadProjects(),loadTasks(),loadRoles(),loadSkills(),loadWorkflows(),searchStandards(),loadAudit()]);setInterval(loadStatus,30000)}
